
### 회원가입
POST http://localhost:8080/join
Content-Type: application/json

{
  "email": "444@naver.com",
  "password": "1",
  "valid": false,
  "userName" : "c",
  "userType": "USER"
}
### 로그인
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "444@naver.com",
  "password": "1"
}

### 로그아웃
POST http://localhost:8080/logout
authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNRjlPdEN2VjU0b1hLMVk2MmZyRU5veEE4dzQzQ240dFgzVndnSStEOXlvPSIsImp0aSI6IjFKNjBWVjlXUmtyTEtKcXk2N3BVSVE9PSIsInJvbGVzIjoiVVNFUiIsImlhdCI6MTY5NTI2NDM5MSwiZXhwIjoxNjk1MjY0OTkxfQ.YQ0nlLD54rpBUJ77FsLhajWT1mOhZWcImL-1nqEU9Xc

### store
POST http://localhost:8080/store
authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNRjlPdEN2VjU0b1hLMVk2MmZyRU5veEE4dzQzQ240dFgzVndnSStEOXlvPSIsImp0aSI6IjFKNjBWVjlXUmtyTEtKcXk2N3BVSVE9PSIsInJvbGVzIjoiVVNFUiIsImlhdCI6MTY5NTM3NDg3NywiZXhwIjoxNjk1Mzc1NDc3fQ.YTfilAZUZugkL9Iewr4ITlTvFK6VdKHgo3jLJVEefDQ

### 파트너 등록
POST http://localhost:8080/reservation/partner/registration
authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNRjlPdEN2VjU0b1hLMVk2MmZyRU5veEE4dzQzQ240dFgzVndnSStEOXlvPSIsImp0aSI6InYzak9vZ1B5RE80em9jaGdrWklLVkE9PSIsInJvbGVzIjoiVVNFUiIsImlhdCI6MTY5NjQxODg0MSwiZXhwIjoxNjk2NDE5NDQxfQ.EC5rsYiBNwUfhL9oNWkIMUFqHR_gdUBRmhf-S1Ehmik
Content-Type: application/json

{
  "email": "dkwktm45@naver.com",
  "partnerName": "게드릉"
}

### 파트너 매장 등록
POST http://localhost:8080/reservation/partner/storeRegist
authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNRjlPdEN2VjU0b1hLMVk2MmZyRU5veEE4dzQzQ240dFgzVndnSStEOXlvPSIsImp0aSI6InYzak9vZ1B5RE80em9jaGdrWklLVkE9PSIsInJvbGVzIjoiVVNFUiIsImlhdCI6MTY5NjQxODg0MSwiZXhwIjoxNjk2NDE5NDQxfQ.EC5rsYiBNwUfhL9oNWkIMUFqHR_gdUBRmhf-S1Ehmik
Content-Type: application/json

{
  "email": "dkwktm45@naver.com",
  "storeDtoList": [
    {
      "storeName": "떡을 볶아볶아56221",
      "storeLocation": "광주 남구3",
      "storeDescription": "떡볶이 맛집",
      "availableSeats": 0,
      "totalSeats": 10
    }
  ]
}

### 매장 목록
GET http://localhost:8080/reservation/store?page=0&size=1
authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoeHVmYmQ0Ui96QXN3a1BWS045bXF3PT0iLCJqdGkiOiI5VjdyUWtoWW1OQUUzTU5BZDhrQ1hRPT0iLCJyb2xlcyI6IlVTRVIiLCJpYXQiOjE2OTY0MTg5MjMsImV4cCI6MTY5NjQxOTUyM30.HMcb6gQ1Ib-Kgq92mdlYuESBhNnDZqGt4MDNi0pUbxI

### 매장 디테일
GET http://localhost:8080/reservation/store/detail?storeName=떡을 볶아볶아56221
authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNRjlPdEN2VjU0b1hLMVk2MmZyRU5veEE4dzQzQ240dFgzVndnSStEOXlvPSIsImp0aSI6InYzak9vZ1B5RE80em9jaGdrWklLVkE9PSIsInJvbGVzIjoiVVNFUiIsImlhdCI6MTY5NjQxODg0MSwiZXhwIjoxNjk2NDE5NDQxfQ.EC5rsYiBNwUfhL9oNWkIMUFqHR_gdUBRmhf-S1Ehmik

### 예약
POST http://localhost:8080/reservation/available
authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoeHVmYmQ0Ui96QXN3a1BWS045bXF3PT0iLCJqdGkiOiI5VjdyUWtoWW1OQUUzTU5BZDhrQ1hRPT0iLCJyb2xlcyI6IlVTRVIiLCJpYXQiOjE2OTY0Mjc3MjEsImV4cCI6MTY5NjQyODMyMX0.jvmFq8thmrHF8U-x12dRAo8AGh4r3P_Mr5niQc1z6MU
Content-Type: application/json

{
  "storeEmail": "dkwktm45@naver.com",
  "storeName": "떡을 볶아볶아56221"
}

### 키오스크 도착
GET http://localhost:8080/reservation/use?reservationId=1&code=b6be30ac-aac4-411f-93ca-c5982764148c
authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJNRjlPdEN2VjU0b1hLMVk2MmZyRU5veEE4dzQzQ240dFgzVndnSStEOXlvPSIsImp0aSI6IjFKNjBWVjlXUmtyTEtKcXk2N3BVSVE9PSIsInJvbGVzIjoiVVNFUiIsImlhdCI6MTY5NTc5MzMzNywiZXhwIjoxNjk1NzkzOTM3fQ.8YBi5DFuIiJuZ-mYrLxC-FiWLnSMFuuEVCjlKQy7LaY

### 알림 유저등록
POST http://localhost:8080/reservation/notification
authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoeHVmYmQ0Ui96QXN3a1BWS045bXF3PT0iLCJqdGkiOiI5VjdyUWtoWW1OQUUzTU5BZDhrQ1hRPT0iLCJyb2xlcyI6IlVTRVIiLCJpYXQiOjE2OTY0Mjc3MjEsImV4cCI6MTY5NjQyODMyMX0.jvmFq8thmrHF8U-x12dRAo8AGh4r3P_Mr5niQc1z6MU
